//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C3PO.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public int cid { get; set; }
        public string name { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string web { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public Nullable<int> countryid { get; set; }
        public string notes { get; set; }
        public int tid { get; set; }
        public int oid { get; set; }
        public Nullable<bool> ispublic { get; set; }
        public string phone { get; set; }
        public string role { get; set; }
        public string report { get; set; }
    }
}
