//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C3PO.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class boarding
    {
        public int? vid { get; set; }
        public int? etid { get; set; }
        public int bid { get; set; }
        public string organization { get; set; }
        public DateTime? startdate { get; set; }
        public DateTime? enddate { get; set; }
        public string mastersafecontents { get; set; }
        public string crewattitude { get; set; }
        public string cargodescription { get; set; }
        public float? latitude { get; set; }
        public float? longitude { get; set; }
        public int? tid { get; set; }
        public int? oid { get; set; }
        public bool? ispublic { get; set; }
        public string activitystated { get; set; }
        public string activitysuspected { get; set; }
        public string unit { get; set; }
        public string eventtype { get; set; }
        public string eventsubtype { get; set; }
        public bool biometricscollected { get; set; }
        public string biometricsreason { get; set; }
        public string uid { get; set; }
        public string methodofcommunicationwithcrew { get; set; }
        public bool? materialgivenaway { get; set; }
        public string favoritehandoutitem { get; set; }
        public int? startdateyear { get; set; }
        public int? startdatemonth { get; set; }
        public int? startdateday { get; set; }
        public int? observedspeed { get; set; }
        public string locationdescription { get; set; }
        public int? starthour { get; set; }
        public int? startminute { get; set; }
        public string report { get; set; }
    
        public virtual vessel vessel { get; set; }
    }
}
