//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C3PO.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public string tribalaffiliation { get; set; }
        public string othernames { get; set; }
        public string placeofbirth { get; set; }
        public string haircolor { get; set; }
        public string eyecolor { get; set; }
        public string gender { get; set; }
        public string race { get; set; }
        public Nullable<int> heightinches { get; set; }
        public Nullable<int> weightlbs { get; set; }
        public int pid { get; set; }
        public string verificationstatus { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTimeOffset> requestsenton { get; set; }
        public Nullable<System.DateTimeOffset> requestreceivedon { get; set; }
        public string tcn { get; set; }
        public string ori { get; set; }
        public string crewposition { get; set; }
        public Nullable<int> oid { get; set; }
        public Nullable<int> tid { get; set; }
        public Nullable<bool> ispublic { get; set; }
        public string fathersname { get; set; }
        public string grandfathersname { get; set; }
        public bool isheightestimated { get; set; }
        public bool isweightestimated { get; set; }
        public bool isdobestimated { get; set; }
        public string primarylanguage { get; set; }
        public Nullable<int> nationalitycid { get; set; }
        public string timeonboard { get; set; }
        public Nullable<bool> isdetained { get; set; }
        public string reasondetained { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string telephonenumber { get; set; }
        public string faxnumber { get; set; }
        public string emailaddress { get; set; }
        public Nullable<int> country { get; set; }
        public Nullable<decimal> dateofbirthyear { get; set; }
        public Nullable<decimal> dateofbirthmonth { get; set; }
        public Nullable<decimal> dateofbirthday { get; set; }
        public string hairstyle { get; set; }
        public string background { get; set; }
        public string facialhair { get; set; }
        public string report { get; set; }
    }
}
