//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C3PO.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vessel
    {
        public vessel()
        {
            this.boardings = new HashSet<boarding>();
        }
    
        public string name { get; set; }
        public string callsign { get; set; }
        public decimal vid { get; set; }
        public string mmsi { get; set; }
        public string imo { get; set; }
        public string sconum { get; set; }
        public float? latitude { get; set; }
        public float? longitude { get; set; }
        public int? typeid { get; set; }
        public float? length { get; set; }
        public string hullcolor { get; set; }
        public string funnelcolor { get; set; }
        public string superstructurecolor { get; set; }
        public int? oid { get; set; }
        public int? tid { get; set; }
        public bool? ispublic { get; set; }
        public string registrationnumber { get; set; }
        public string externalmarkings { get; set; }
        public string inmarsat { get; set; }
        public string fueloilstatus { get; set; }
        public string dailyfueloilconsumption { get; set; }
        public string fuelloadedcost { get; set; }
        public string plantstatus { get; set; }
        public float? beam { get; set; }
        public float? draft { get; set; }
        public bool islengthestimated { get; set; }
        public bool isbeamestimated { get; set; }
        public bool isdraftestimated { get; set; }
        public string lastportofcall { get; set; }
        public bool? hassatphones { get; set; }
        public bool? hascellphones { get; set; }
        public int? crewtotal { get; set; }
        public int? skiffs { get; set; }
        public string portofregistry { get; set; }
        public string nextportofcall { get; set; }
        public string pilothousedescription { get; set; }
        public int? flagcid { get; set; }
        public int? lastportofcallcid { get; set; }
        public int? registrycid { get; set; }
        public int? nextportofcallcid { get; set; }
        public bool? securityteamaboard { get; set; }
        public int? securityteamsize { get; set; }
        public bool? securityteampartofcrew { get; set; }
        public int? fueltypeid { get; set; }
        public string hiddencompartments { get; set; }
        public string explosivesdetected { get; set; }
        public string normaltradingroute { get; set; }
        public bool? aisrequired { get; set; }
        public bool? aisonboard { get; set; }
        public bool? aisfunctional { get; set; }
        public bool? aiscorrect { get; set; }
        public decimal? etayear { get; set; }
        public decimal? etamonth { get; set; }
        public decimal? etaday { get; set; }
        public decimal? lastportofcallyear { get; set; }
        public decimal? lastportofcallmonth { get; set; }
        public decimal? lastportofcallday { get; set; }
        public bool? aisison { get; set; }
        public string condition { get; set; }
        public string capabilities { get; set; }
        public string material { get; set; }
        public string conditionnotes { get; set; }
        public string report { get; set; }
    
        public virtual ICollection<boarding> boardings { get; set; }
    }
}
